name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install --force
      - run: npm run build
      - run: git config --global user.name "6ocra3"
      - run: git config --global user.email "6o3kmm@mail.ru"
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: master
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
